name: Build/Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  cargo-build-test:
    name: Cargo build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features: [std, no_std]
      fail-fast: false

    # allow for cache to be shared between jobs
    concurrency: cargodeps-${{ matrix.features }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain (stable)
        run: rustup update stable --no-self-update
      - name: Set up Rust artifact cache
        uses: actions/cache@v4
        with:
          # cache can be shared between crates since it's workspace-global, still partition by features though
          key: cargodeps-${{ matrix.features }}-${{ hashFiles('**/Cargo.toml') }}
          # Cargo paths came from https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          # (we don't `cargo install` anything so I think it should be fine to ignore the other paths)
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
      - name: Build & test protocol crate
        env:
          FEATURE_FLAGS: ${{ matrix.features == 'no_std' && '--no-default-features' || '' }}
        run: |
          cargo build --package tacacs-plus-protocol --verbose $FEATURE_FLAGS
          cargo test --package tacacs-plus-protocol --verbose $FEATURE_FLAGS
      - name: Build & test client crate
        if: ${{ matrix.features == 'std' }}
        run: |
          cargo build --package tacacs-plus --verbose
          # only test lib/doc tests; integration tests need a dedicated server
          cargo test --package tacacs-plus --lib --verbose
          cargo test --package tacacs-plus --doc --verbose
      - name: Setup Docker Buildx builder
        if: ${{ matrix.features == 'std' }}
        uses: docker/setup-buildx-action@v3
        with:
          use: true
          install: true
      - name: Build test server image (Shrubbery)
        if: ${{ matrix.features == 'std' }}
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          load: true
          context: ./test-assets/
          target: tacacs-shrubbery-configured
          tags: localhost/tacacs-shrubbery-server
      - name: Build test server image (TACACS+ NG)
        if: ${{ matrix.features == 'std' }}
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          load: true
          context: ./test-assets/
          target: tacacs-ng-configured
          tags: localhost/tacacs-ng-server
      - name: Run client tests against server
        if: ${{ matrix.features == 'std' }}
        env:
          TMPDIR: ${{ runner.temp }}
        run: ./test-assets/run-client-tests.sh
